language: node_js
node_js:
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16 
  - 17
script:  
  - npm run ci
after_script: 
  - npm i coveralls
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
